// ideacircuit-web/src/components/Navbar.tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { MenuIcon, XIcon, PresentationIcon, BarChart2Icon, UserIcon } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';

export const Navbar: React.FC = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const { isAuthenticated } = useAuth();

  return (
    <nav className="glass-subtle py-4 px-6 lg:px-12 sticky top-0 z-50 border-b border-border transition-all duration-normal">
      <div className="max-w-7xl mx-auto">
        <div className="flex justify-between items-center">
          <div className="flex items-center">
            <Link to="/" className="text-display-small font-bold text-primary hover:text-primary-hover transition-colors duration-fast">
              IdeaCircuit
            </Link>
          </div>
          <div className="hidden md:flex items-center space-x-8">
            <a href="#features" className="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast">
              Features
            </a>
            <a href="#pricing" className="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast">
              Pricing
            </a>
            <a href="#testimonials" className="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast">
              Reviews
            </a>
            {/* Application Pages */}
            <div className="flex items-center space-x-4 border-l border-border pl-4">
              <Link 
                to="/presentation" 
                className="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
              >
                <PresentationIcon size={16} />
                <span>Presentation</span>
              </Link>
              <Link 
                to="/report" 
                className="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
              >
                <BarChart2Icon size={16} />
                <span>Reports</span>
              </Link>
              {isAuthenticated ? (
                <Link 
                  to="/profile" 
                  className="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
                >
                  <UserIcon size={16} />
                  <span>Profile</span>
                </Link>
              ) : (
                <Link 
                  to="/login" 
                  className="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
                >
                  <UserIcon size={16} />
                  <span>Login</span>
                </Link>
              )}
            </div>
            {!isAuthenticated && (
              <Link 
                to="/signup" 
                className="bg-primary text-white px-6 py-3 rounded-md font-medium text-label min-h-[44px] flex items-center hover:bg-primary-hover transition-colors duration-fast"
              >
                Get Started
              </Link>
            )}
          </div>
          <div className="md:hidden">
            <button 
              type="button" 
              className="text-text-secondary hover:text-text-primary focus:outline-none min-h-[44px] min-w-[44px] flex items-center justify-center transition-colors duration-fast"
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              aria-label="Toggle menu"
            >
              {isMenuOpen ? <XIcon size={24} /> : <MenuIcon size={24} />}
            </button>
          </div>
        </div>
        
        {/* Mobile menu */}
        {isMenuOpen && (
          <div className="md:hidden mt-4 glass-subtle border-t border-border pt-4">
            <div className="flex flex-col space-y-4 pb-4">
              <a 
                href="#features" 
                className="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast" 
                onClick={() => setIsMenuOpen(false)}
              >
                Features
              </a>
              <a 
                href="#pricing" 
                className="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast" 
                onClick={() => setIsMenuOpen(false)}
              >
                Pricing
              </a>
              <a 
                href="#testimonials" 
                className="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast" 
                onClick={() => setIsMenuOpen(false)}
              >
                Reviews
              </a>
              {/* Application Pages */}
              <div className="border-t border-border pt-4">
                <div className="text-caption font-semibold text-text-tertiary mb-2">Application</div>
                <Link 
                  to="/presentation" 
                  className="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
                  onClick={() => setIsMenuOpen(false)}
                >
                  <PresentationIcon size={16} />
                  <span>Presentation</span>
                </Link>
                <Link 
                  to="/report" 
                  className="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
                  onClick={() => setIsMenuOpen(false)}
                >
                  <BarChart2Icon size={16} />
                  <span>Reports</span>
                </Link>
                {isAuthenticated ? (
                  <Link 
                    to="/profile" 
                    className="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
                    onClick={() => setIsMenuOpen(false)}
                  >
                    <UserIcon size={16} />
                    <span>Profile</span>
                  </Link>
                ) : (
                  <Link 
                    to="/login" 
                    className="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
                    onClick={() => setIsMenuOpen(false)}
                  >
                    <UserIcon size={16} />
                    <span>Login</span>
                  </Link>
                )}
              </div>
              {!isAuthenticated && (
                <Link 
                  to="/signup" 
                  className="bg-primary text-white px-6 py-3 rounded-md font-medium text-label min-h-[44px] flex items-center justify-center hover:bg-primary-hover transition-colors duration-fast" 
                  onClick={() => setIsMenuOpen(false)}
                >
                  Get Started
                </Link>
              )}
            </div>
          </div>
        )}
      </div>
    </nav>
  );
};

// ideacircuit-web/src/components/Navbar.vue
<template>
  <nav class="glass-subtle py-4 px-6 lg:px-12 sticky top-0 z-50 border-b border-border transition-all duration-normal">
    <div class="max-w-7xl mx-auto">
      <div class="flex justify-between items-center">
        <div class="flex items-center">
          <router-link to="/" class="text-display-small font-bold text-primary hover:text-primary-hover transition-colors duration-fast">
            IdeaCircuit
          </router-link>
        </div>
        <div class="hidden md:flex items-center space-x-8">
          <a href="#features" class="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast">
            Features
          </a>
          <a href="#pricing" class="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast">
            Pricing
          </a>
          <a href="#testimonials" class="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast">
            Reviews
          </a>
          <!-- Application Pages -->
          <div class="flex items-center space-x-4 border-l border-border pl-4">
            <router-link 
              to="/presentation" 
              class="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
            >
              <PresentationIcon :size="16" />
              <span>Presentation</span>
            </router-link>
            <router-link 
              to="/report" 
              class="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
            >
              <BarChart2Icon :size="16" />
              <span>Reports</span>
            </router-link>
            <router-link 
              v-if="isAuthenticated"
              to="/profile" 
              class="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
            >
              <UserIcon :size="16" />
              <span>Profile</span>
            </router-link>
            <router-link 
              v-else
              to="/login" 
              class="flex items-center space-x-1 text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast"
            >
              <UserIcon :size="16" />
              <span>Login</span>
            </router-link>
          </div>
          <Button
            v-if="!isAuthenticated"
            as-child
            variant="default"
            class="min-h-[44px]"
          >
            <router-link to="/signup">
              Get Started
            </router-link>
          </Button>
        </div>
        <div class="md:hidden">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            class="min-h-[44px] min-w-[44px]"
            @click="isMenuOpen = !isMenuOpen"
            aria-label="Toggle menu"
          >
            <XIcon v-if="isMenuOpen" :size="24" />
            <MenuIcon v-else :size="24" />
          </Button>
        </div>
      </div>
      
      <!-- Mobile menu -->
      <div v-if="isMenuOpen" class="md:hidden mt-4 glass-subtle border-t border-border pt-4">
        <div class="flex flex-col space-y-4 pb-4">
          <a 
            href="#features" 
            class="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast" 
            @click="isMenuOpen = false"
          >
            Features
          </a>
          <a 
            href="#pricing" 
            class="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast" 
            @click="isMenuOpen = false"
          >
            Pricing
          </a>
          <a 
            href="#testimonials" 
            class="text-text-secondary hover:text-primary font-medium text-body-medium transition-colors duration-fast" 
            @click="isMenuOpen = false"
          >
            Reviews
          </a>
          <!-- Application Pages -->
          <div class="border-t border-border pt-4">
            <div class="text-caption font-semibold text-text-tertiary mb-2">Application</div>
            <router-link 
              to="/presentation" 
              class="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
              @click="isMenuOpen = false"
            >
              <PresentationIcon :size="16" />
              <span>Presentation</span>
            </router-link>
            <router-link 
              to="/report" 
              class="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
              @click="isMenuOpen = false"
            >
              <BarChart2Icon :size="16" />
              <span>Reports</span>
            </router-link>
            <router-link 
              v-if="isAuthenticated"
              to="/profile" 
              class="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
              @click="isMenuOpen = false"
            >
              <UserIcon :size="16" />
              <span>Profile</span>
            </router-link>
            <router-link 
              v-else
              to="/login" 
              class="flex items-center space-x-2 text-text-secondary hover:text-primary font-medium text-body-medium py-2 transition-colors duration-fast" 
              @click="isMenuOpen = false"
            >
              <UserIcon :size="16" />
              <span>Login</span>
            </router-link>
          </div>
          <Button
            v-if="!isAuthenticated"
            as-child
            variant="default"
            class="min-h-[44px]"
            @click="isMenuOpen = false"
          >
            <router-link to="/signup">
              Get Started
            </router-link>
          </Button>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { MenuIcon, XIcon, PresentationIcon, BarChart2Icon, UserIcon } from 'lucide-vue-next';
import { useAuth } from '@/composables/useAuth';
import { Button } from '@/components/ui';

const { isAuthenticated } = useAuth();
const isMenuOpen = ref(false);
</script>
