// ideacircuit-web/src/components/NavigationMenu.vue
<template>
  <div class="relative" ref="menuRef">
    <button
      @click="toggleMenu"
      class="text-white hover:text-gray-300 focus:outline-none min-h-[44px] min-w-[44px] flex items-center justify-center transition-colors duration-fast"
      aria-label="Toggle navigation menu"
    >
      <MenuIcon v-if="!isOpen" :size="24" />
      <XIcon v-else :size="24" />
    </button>
    
    <div
      v-if="isOpen"
      class="absolute right-0 mt-2 w-64 glass-prominent rounded-lg shadow-xl border border-border z-50 overflow-hidden"
    >
      <div class="p-2">
        <div
          v-for="(group, groupKey) in groupedMenuItems"
          :key="groupKey"
          class="mb-2 last:mb-0"
        >
          <div v-if="groupKey !== 'main'" class="px-3 py-2 text-caption font-semibold text-text-tertiary uppercase">
            {{ groupKey }}
          </div>
          <router-link
            v-for="item in group"
            :key="item.path"
            :to="item.path"
            @click="isOpen = false"
            class="flex items-center space-x-3 px-3 py-2 rounded-md text-body-medium text-text-secondary hover:bg-bg-tertiary hover:text-text-primary transition-colors duration-fast min-h-[44px]"
            active-class="bg-primary/10 text-primary"
          >
            <component :is="item.iconComponent" :size="18" />
            <span>{{ item.label }}</span>
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import {
  MenuIcon,
  XIcon,
  HomeIcon,
  PresentationIcon,
  BarChart2Icon,
  TrendingUpIcon,
  BriefcaseIcon,
  DatabaseIcon,
  FileTextIcon,
  NetworkIcon,
  FolderIcon,
  UserIcon,
  LogInIcon,
  UserPlusIcon,
  CalendarIcon,
  BotIcon
} from 'lucide-vue-next';

interface MenuItem {
  path: string;
  label: string;
  iconComponent: any;
  category?: string;
}

const isOpen = ref(false);
const menuRef = ref<HTMLElement | null>(null);

const toggleMenu = () => {
  isOpen.value = !isOpen.value;
};

const menuItems: MenuItem[] = [
  {
    path: '/',
    label: 'Video Call',
    iconComponent: HomeIcon,
    category: 'AI Meetings'
  },
  {
    path: '/presentation',
    label: 'Presentation',
    iconComponent: PresentationIcon,
    category: 'Meeting Tools'
  },
  {
    path: '/report',
    label: 'Data Report',
    iconComponent: BarChart2Icon,
    category: 'Meeting Tools'
  },
  {
    path: '/marketing-report',
    label: 'Marketing Report',
    iconComponent: TrendingUpIcon,
    category: 'Meeting Tools'
  },
  {
    path: '/business-profile',
    label: 'Business Profile',
    iconComponent: BriefcaseIcon,
    category: 'Meeting Tools'
  },
  {
    path: '/data-analytics',
    label: 'Data Analytics',
    iconComponent: DatabaseIcon,
    category: 'Meeting Tools'
  },
  {
    path: '/client-proposal',
    label: 'Client Proposal',
    iconComponent: FileTextIcon,
    category: 'Meeting Tools'
  },
  {
    path: '/ai-workflow',
    label: 'AI Workflow',
    iconComponent: NetworkIcon,
    category: 'Meeting Tools'
  },
  {
    path: '/files',
    label: 'My Files',
    iconComponent: FolderIcon,
    category: 'My Account'
  },
  {
    path: '/schedule',
    label: 'Schedule Calls',
    iconComponent: CalendarIcon,
    category: 'My Account'
  },
  {
    path: '/profile',
    label: 'My Profile',
    iconComponent: UserIcon,
    category: 'My Account'
  },
  {
    path: '/login',
    label: 'Login',
    iconComponent: LogInIcon,
    category: 'Authentication'
  },
  {
    path: '/signup',
    label: 'Sign Up',
    iconComponent: UserPlusIcon,
    category: 'Authentication'
  }
];

const groupedMenuItems = computed(() => {
  const grouped: Record<string, MenuItem[]> = {};
  menuItems.forEach(item => {
    const category = item.category || 'main';
    if (!grouped[category]) {
      grouped[category] = [];
    }
    grouped[category].push(item);
  });
  return grouped;
});

const handleClickOutside = (event: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
};

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});
</script>

// ideacircuit-web/src/components/NavigationMenu.tsx
import React, { useEffect, useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import { MenuIcon, HomeIcon, PresentationIcon, BarChart2Icon, TrendingUpIcon, BriefcaseIcon, DatabaseIcon, XIcon, FileTextIcon, NetworkIcon, FolderIcon, UserIcon, LogInIcon, UserPlusIcon, CalendarIcon, ClockIcon, BotIcon } from 'lucide-react';
export const NavigationMenu = () => {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef(null);
  const toggleMenu = () => {
    setIsOpen(!isOpen);
  };
  // Close menu when clicking outside
  useEffect(() => {
    const handleClickOutside = event => {
      if (menuRef.current && !menuRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);
  const menuItems = [{
    path: '/',
    label: 'Video Call',
    icon: <HomeIcon size={18} />
  }, {
    path: '/presentation',
    label: 'Presentation',
    icon: <PresentationIcon size={18} />
  }, {
    path: '/report',
    label: 'Data Report',
    icon: <BarChart2Icon size={18} />
  }, {
    path: '/marketing-report',
    label: 'Marketing Report',
    icon: <TrendingUpIcon size={18} />
  }, {
    path: '/business-profile',
    label: 'Business Profile',
    icon: <BriefcaseIcon size={18} />
  }, {
    path: '/data-analytics',
    label: 'Data Analytics',
    icon: <DatabaseIcon size={18} />
  }, {
    path: '/client-proposal',
    label: 'Client Proposal',
    icon: <FileTextIcon size={18} />
  }, {
    path: '/ai-workflow',
    label: 'AI Workflow',
    icon: <NetworkIcon size={18} />
  }, {
    path: '/fae-create',
    label: 'Create FAE Solution',
    icon: <BotIcon size={18} />
  }, {
    path: '/files',
    label: 'My Files',
    icon: <FolderIcon size={18} />
  }, {
    path: '/schedule',
    label: 'Schedule Calls',
    icon: <CalendarIcon size={18} />
  }, {
    path: '/profile',
    label: 'My Profile',
    icon: <UserIcon size={18} />
  }, {
    path: '/login',
    label: 'Login',
    icon: <LogInIcon size={18} />
  }, {
    path: '/signup',
    label: 'Sign Up',
    icon: <UserPlusIcon size={18} />
  }];
  // Group menu items by category
  const groupedMenuItems = {
    'AI Meetings': menuItems.slice(0, 1),
    'Meeting Tools': menuItems.slice(1, 9),
    'My Account': menuItems.slice(9, 12),
    Authentication: menuItems.slice(12, 14)
  };
  return <div className="relative" ref={menuRef}>
      <button onClick={toggleMenu} className="p-2 rounded-full hover:bg-gray-700 transition-colors" aria-label="Navigation menu">
        {isOpen ? <XIcon size={20} /> : <MenuIcon size={20} />}
      </button>
      {isOpen && <div className="absolute right-0 mt-2 w-64 bg-white rounded-md shadow-lg z-50 overflow-hidden">
          <div className="py-1">
            {Object.entries(groupedMenuItems).map(([category, items]) => <div key={category}>
                <div className="px-4 py-2 text-xs font-semibold text-gray-500 bg-gray-50">
                  {category}
                </div>
                {items.map(item => <Link key={item.path} to={item.path} className="flex items-center px-4 py-3 text-gray-800 hover:bg-gray-100" onClick={() => setIsOpen(false)}>
                    <span className="mr-3 text-gray-600">{item.icon}</span>
                    {item.label}
                  </Link>)}
              </div>)}
          </div>
        </div>}
    </div>;
};
