// _legacy_apps/ideacircuit-web/src/components/NotesPanel.vue
<template>
  <div class="h-full flex flex-col">
    <div class="p-3 glass-subtle border-b border-border font-medium text-title-medium text-text-primary flex justify-between items-center">
      <span>Meeting Notes</span>
      <button
        v-if="onAddCategory"
        @click="isAddingCategory = true"
        class="text-primary hover:text-primary-hover text-label font-medium flex items-center transition-colors duration-fast"
        aria-label="Add category"
      >
        <PlusIcon :size="16" class="mr-1" /> Add Category
      </button>
    </div>

    <div v-if="isAddingCategory" class="p-3 bg-primary-light border-b border-border flex items-center gap-2">
      <Input
        v-model="newCategory"
        type="text"
        class="flex-1"
        placeholder="New category name"
        @keypress.enter="handleAddCategory"
      />
      <Button
        @click="handleAddCategory"
        aria-label="Add category"
        class="min-h-[44px]"
      >
        Add
      </Button>
      <Button
        variant="ghost"
        size="icon"
        @click="cancelAddCategory"
        aria-label="Cancel"
        class="min-h-[44px] min-w-[44px]"
      >
        <XIcon :size="16" />
      </Button>
    </div>

    <div class="flex-1 overflow-y-auto p-6 space-y-6">
      <div v-if="notes.length === 0" class="text-center py-8 text-text-secondary">
        <p class="text-body-medium">No notes yet. Add a category to get started.</p>
      </div>
      <div v-else>
        <div
          v-for="(note, index) in notes"
          :key="index"
          class="glass-standard rounded-lg overflow-hidden shadow-1"
        >
          <div class="bg-bg-secondary p-3 font-medium text-title-medium text-text-primary border-b border-border">
            {{ note.category }}
          </div>
          <ul class="p-3 space-y-2">
            <li
              v-for="(item, itemIndex) in note.items"
              :key="itemIndex"
              class="flex items-start"
            >
              <span class="inline-block w-2 h-2 rounded-full bg-primary mt-2 mr-2 flex-shrink-0"></span>
              <span class="text-body-medium text-text-primary flex-1">{{ item.text }}</span>
              <span v-if="item.timestamp" class="text-caption text-text-secondary ml-2">{{ item.timestamp }}</span>
            </li>
          </ul>
          <div v-if="onAddNote" class="p-3 border-t border-border">
            <div class="flex items-center gap-2">
              <Input
                v-model="newItemText[note.category]"
                type="text"
                class="flex-1"
                placeholder="Add a note..."
                @keypress.enter="handleAddItem(note.category)"
              />
              <Button
                @click="handleAddItem(note.category)"
                aria-label="Add note"
                class="min-h-[44px]"
              >
                Add
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { PlusIcon, XIcon } from 'lucide-vue-next';
import { Input, Button } from '@/components/ui';

interface NoteItem {
  text: string;
  timestamp?: string;
}

interface NoteCategory {
  category: string;
  items: NoteItem[];
}

interface Props {
  notes: NoteCategory[];
  onAddNote?: (category: string, text: string) => void;
  onAddCategory?: (categoryName: string) => void;
}

const props = defineProps<Props>();

const newCategory = ref('');
const isAddingCategory = ref(false);
const newItemText = ref<{ [key: string]: string }>({});

const handleAddCategory = () => {
  if (newCategory.value.trim() && props.onAddCategory) {
    props.onAddCategory(newCategory.value.trim());
    newCategory.value = '';
    isAddingCategory.value = false;
  }
};

const cancelAddCategory = () => {
  isAddingCategory.value = false;
  newCategory.value = '';
};

const handleAddItem = (category: string) => {
  const text = newItemText.value[category]?.trim();
  if (text && props.onAddNote) {
    props.onAddNote(category, text);
    newItemText.value = { ...newItemText.value, [category]: '' };
  }
};
</script>

// ideacircuit-web/src/components/NotesPanel.tsx
import React, { useState } from 'react';
import { PlusIcon, XIcon } from 'lucide-react';

interface NoteItem {
  text: string;
  timestamp?: string;
}

interface NoteCategory {
  category: string;
  items: NoteItem[];
}

interface NotesPanelProps {
  notes: NoteCategory[];
  onAddNote?: (category: string, text: string) => void;
  onAddCategory?: (categoryName: string) => void;
}

export const NotesPanel: React.FC<NotesPanelProps> = ({ notes, onAddNote, onAddCategory }) => {
  const [newCategory, setNewCategory] = useState('');
  const [isAddingCategory, setIsAddingCategory] = useState(false);
  const [newItemText, setNewItemText] = useState<{ [key: string]: string }>({});

  const handleAddCategory = () => {
    if (newCategory.trim() && onAddCategory) {
      onAddCategory(newCategory.trim());
      setNewCategory('');
      setIsAddingCategory(false);
    }
  };

  const handleAddItem = (category: string) => {
    const text = newItemText[category]?.trim();
    if (text && onAddNote) {
      onAddNote(category, text);
      setNewItemText({ ...newItemText, [category]: '' });
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="p-3 glass-subtle border-b border-border font-medium text-title-medium text-text-primary flex justify-between items-center">
        <span>Meeting Notes</span>
        {onAddCategory && (
          <button 
            onClick={() => setIsAddingCategory(true)} 
            className="text-primary hover:text-primary-hover text-label font-medium flex items-center transition-colors duration-fast"
            aria-label="Add category"
          >
            <PlusIcon size={16} className="mr-1" /> Add Category
          </button>
        )}
      </div>
      
      {isAddingCategory && (
        <div className="p-3 bg-primary-light border-b border-border flex items-center gap-2">
          <input 
            type="text" 
            className="flex-1 border border-border rounded-md px-3 py-2 text-body-medium bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" 
            placeholder="New category name" 
            value={newCategory} 
            onChange={e => setNewCategory(e.target.value)}
            onKeyPress={e => e.key === 'Enter' && handleAddCategory()}
          />
          <button 
            className="bg-primary text-white px-3 py-2 rounded-md text-label font-medium min-h-[44px] hover:bg-primary-hover transition-colors duration-fast" 
            onClick={handleAddCategory}
            aria-label="Add category"
          >
            Add
          </button>
          <button 
            className="text-text-secondary hover:text-text-primary p-2 min-h-[44px] min-w-[44px] flex items-center justify-center" 
            onClick={() => {
              setIsAddingCategory(false);
              setNewCategory('');
            }}
            aria-label="Cancel"
          >
            <XIcon size={16} />
          </button>
        </div>
      )}
      
      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {notes.length === 0 ? (
          <div className="text-center py-8 text-text-secondary">
            <p className="text-body-medium">No notes yet. Add a category to get started.</p>
          </div>
        ) : (
          notes.map((note, index) => (
            <div key={index} className="glass-standard rounded-lg overflow-hidden shadow-1">
              <div className="bg-bg-secondary p-3 font-medium text-title-medium text-text-primary border-b border-border">
                {note.category}
              </div>
              <ul className="p-3 space-y-2">
                {note.items.map((item, itemIndex) => (
                  <li key={itemIndex} className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full bg-primary mt-2 mr-2 flex-shrink-0"></span>
                    <span className="text-body-medium text-text-primary">{item.text}</span>
                  </li>
                ))}
                {onAddNote && (
                  <li className="pt-2">
                    <div className="flex items-center gap-2">
                      <input
                        type="text"
                        className="flex-1 border border-border rounded-md px-3 py-2 text-body-medium bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                        placeholder="Add item..."
                        value={newItemText[note.category] || ''}
                        onChange={e => setNewItemText({ ...newItemText, [note.category]: e.target.value })}
                        onKeyPress={e => e.key === 'Enter' && handleAddItem(note.category)}
                      />
                      <button 
                        className="text-primary hover:text-primary-hover text-label font-medium flex items-center transition-colors duration-fast"
                        onClick={() => handleAddItem(note.category)}
                        aria-label="Add item"
                      >
                        <PlusIcon size={16} className="mr-1" /> Add
                      </button>
                    </div>
                  </li>
                )}
              </ul>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
