// ideacircuit-web/src/components/RecordButton.vue
<template>
  <div class="relative">
    <Button
      @click="toggleRecording"
      :disabled="recordingStatus === 'processing'"
      :variant="isRecording ? 'destructive' : 'secondary'"
      size="icon"
      :class="`rounded-full min-h-[44px] min-w-[44px] ${
        isRecording ? 'animate-pulse' : ''
      }`"
    >
      <LoaderIcon v-if="recordingStatus === 'processing'" :size="20" class="animate-spin" />
      <StopCircleIcon v-else-if="isRecording" :size="20" />
      <MicIcon v-else :size="20" />
    </Button>
    <Badge
      v-if="isRecording"
      variant="destructive"
      class="absolute -top-8 left-1/2 transform -translate-x-1/2 whitespace-nowrap"
    >
      {{ formatTime(recordingTime) }}
    </Badge>
    <Badge
      v-if="recordingStatus === 'complete'"
      variant="default"
      class="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-green-500 text-white whitespace-nowrap"
    >
      Recording saved
    </Badge>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted } from 'vue';
import { StopCircleIcon, LoaderIcon, MicIcon } from 'lucide-vue-next';
import { Button, Badge } from '@/components/ui';

interface Props {
  onRecordingComplete?: (data: { duration: number; date: string; filename: string }) => void;
}

const props = defineProps<Props>();

const isRecording = ref(false);
const recordingTime = ref(0);
const recordingStatus = ref<'idle' | 'recording' | 'processing' | 'complete'>('idle');

let interval: ReturnType<typeof setInterval> | null = null;

const formatTime = (seconds: number) => {
  const mins = Math.floor(seconds / 60).toString().padStart(2, '0');
  const secs = (seconds % 60).toString().padStart(2, '0');
  return `${mins}:${secs}`;
};

const toggleRecording = () => {
  if (isRecording.value) {
    isRecording.value = false;
    recordingStatus.value = 'processing';
    if (interval) {
      clearInterval(interval);
      interval = null;
    }
    setTimeout(() => {
      recordingStatus.value = 'complete';
      if (props.onRecordingComplete) {
        props.onRecordingComplete({
          duration: recordingTime.value,
          date: new Date().toISOString(),
          filename: `recording-${new Date().toISOString().substring(0, 10)}.mp4`
        });
      }
    }, 2000);
  } else {
    recordingTime.value = 0;
    isRecording.value = true;
    recordingStatus.value = 'recording';
  }
};

watch(isRecording, (recording) => {
  if (recording) {
    interval = setInterval(() => {
      recordingTime.value++;
    }, 1000);
  } else if (interval) {
    clearInterval(interval);
    interval = null;
  }
});

onUnmounted(() => {
  if (interval) {
    clearInterval(interval);
  }
});
</script>

// ideacircuit-web/src/components/RecordButton.tsx
import React, { useEffect, useState } from 'react';
import { StopCircleIcon, LoaderIcon, MicIcon } from 'lucide-react';

export const RecordButton = ({
  onRecordingComplete
}: {
  onRecordingComplete?: (data: { duration: number; date: string; filename: string }) => void;
}) => {
  const [isRecording, setIsRecording] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [recordingStatus, setRecordingStatus] = useState('idle'); // idle, recording, processing, complete

  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    if (isRecording) {
      interval = setInterval(() => {
        setRecordingTime(prev => prev + 1);
      }, 1000);
    } else if (!isRecording && recordingTime !== 0) {
      clearInterval(interval);
    }
    return () => clearInterval(interval);
  }, [isRecording, recordingTime]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60).toString().padStart(2, '0');
    const secs = (seconds % 60).toString().padStart(2, '0');
    return `${mins}:${secs}`;
  };

  const toggleRecording = () => {
    if (isRecording) {
      // Stop recording
      setIsRecording(false);
      setRecordingStatus('processing');
      // Simulate processing time
      setTimeout(() => {
        setRecordingStatus('complete');
        if (onRecordingComplete) {
          onRecordingComplete({
            duration: recordingTime,
            date: new Date().toISOString(),
            filename: `recording-${new Date().toISOString().substring(0, 10)}.mp4`
          });
        }
      }, 2000);
    } else {
      // Start recording
      setRecordingTime(0);
      setIsRecording(true);
      setRecordingStatus('recording');
    }
  };

  return (
    <div className="relative">
      <button
        onClick={toggleRecording}
        disabled={recordingStatus === 'processing'}
        className={`p-3 rounded-full flex items-center justify-center relative
          ${isRecording ? 'bg-red-500 text-white animate-pulse' : recordingStatus === 'processing' ? 'bg-gray-400 text-white' : 'bg-gray-600 hover:bg-gray-500 text-white'}`}
      >
        {recordingStatus === 'processing' ? (
          <LoaderIcon size={20} className="animate-spin" />
        ) : isRecording ? (
          <StopCircleIcon size={20} />
        ) : (
          <MicIcon size={20} />
        )}
      </button>
      {isRecording && (
        <div className="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-red-500 text-white text-xs px-2 py-1 rounded-md whitespace-nowrap">
          {formatTime(recordingTime)}
        </div>
      )}
      {recordingStatus === 'complete' && (
        <div className="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-green-500 text-white text-xs px-2 py-1 rounded-md whitespace-nowrap">
          Recording saved
        </div>
      )}
    </div>
  );
};
