// coordinator-web/src/components/onboarding/RoleSelectionStep.vue
<template>
  <div class="w-full">
    <div class="text-center mb-8">
      <h1 class="text-3xl md:text-4xl font-heading font-bold text-[#1B4F72] mb-2">
        Choose Your Coordinator
      </h1>
      <p class="text-lg text-slate-600">
        What role do you need help with?
      </p>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
      <!-- Inbound Column -->
      <div class="space-y-4">
        <div class="flex items-center gap-3 mb-4 px-1">
          <div class="h-px flex-1 bg-slate-200"></div>
          <h2 class="text-sm font-bold text-slate-400 uppercase tracking-wider">
            Inbound Roles
          </h2>
          <div class="h-px flex-1 bg-slate-200"></div>
        </div>
        <div class="grid grid-cols-1 gap-3">
          <RoleCard
            v-for="role in inboundRoles"
            :key="role.id"
            :id="role.id"
            :title="role.title"
            :price="role.price"
            :description="role.description"
            :icon="role.icon"
            :selected="selectedRole === role.id"
            @select="selectedRole = role.id"
          />
        </div>
      </div>

      <!-- Outbound Column -->
      <div class="space-y-4">
        <div class="flex items-center gap-3 mb-4 px-1">
          <div class="h-px flex-1 bg-slate-200"></div>
          <h2 class="text-sm font-bold text-slate-400 uppercase tracking-wider">
            Outbound Roles
          </h2>
          <div class="h-px flex-1 bg-slate-200"></div>
        </div>
        <div class="grid grid-cols-1 gap-3">
          <RoleCard
            v-for="role in outboundRoles"
            :key="role.id"
            :id="role.id"
            :title="role.title"
            :price="role.price"
            :description="role.description"
            :icon="role.icon"
            :selected="selectedRole === role.id"
            @select="selectedRole = role.id"
          />
        </div>
      </div>
    </div>

    <!-- Continue Button -->
    <div class="mt-10 flex justify-end">
      <button
        @click="handleNext"
        :disabled="!selectedRole"
        class="px-8 py-3 bg-[#1B4F72] hover:bg-[#153e5a] text-white font-semibold rounded-lg shadow-md hover:shadow-lg transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
      >
        Continue
        <ArrowRight :size="18" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import {
  Phone,
  Calendar,
  Truck,
  Utensils,
  Headset,
  Shield,
  CheckCircle,
  TrendingUp,
  DollarSign,
  Megaphone,
  ClipboardList,
  ArrowRight,
} from 'lucide-vue-next';
import RoleCard from './RoleCard.vue';
import { onboardingApi, type RoleTemplate } from '@/api/onboarding';

const emit = defineEmits<{
  next: [data: { role_template_id: string }];
}>();

const selectedRole = ref<string | null>(null);
const roleTemplates = ref<RoleTemplate[]>([]);
const loading = ref(true);

// Icon mapping for role types
const iconMap: Record<string, any> = {
  receptionist: Phone,
  scheduler: Calendar,
  dispatcher: Truck,
  hostess: Utensils,
  support: Headset,
  tipline: Shield,
  confirmer: CheckCircle,
  sales: TrendingUp,
  collector: DollarSign,
  introducer: Megaphone,
  survey: ClipboardList,
};

const inboundRoles = computed(() => {
  return roleTemplates.value
    .filter(role => role.name.toLowerCase().includes('receptionist') || 
                   role.name.toLowerCase().includes('scheduler') ||
                   role.name.toLowerCase().includes('dispatcher') ||
                   role.name.toLowerCase().includes('hostess') ||
                   role.name.toLowerCase().includes('support') ||
                   role.name.toLowerCase().includes('tipline'))
    .map(role => ({
      id: role.id,
      title: role.name,
      price: `$${role.base_price}/mo`,
      description: role.description || '',
      icon: iconMap[role.name.toLowerCase().replace(/\s+/g, '')] || Phone,
    }));
});

const outboundRoles = computed(() => {
  return roleTemplates.value
    .filter(role => role.name.toLowerCase().includes('confirmer') ||
                   role.name.toLowerCase().includes('sales') ||
                   role.name.toLowerCase().includes('collector') ||
                   role.name.toLowerCase().includes('introducer') ||
                   role.name.toLowerCase().includes('survey'))
    .map(role => ({
      id: role.id,
      title: role.name,
      price: `$${role.base_price}/mo`,
      description: role.description || '',
      icon: iconMap[role.name.toLowerCase().replace(/\s+/g, '')] || CheckCircle,
    }));
});

function handleNext() {
  if (selectedRole.value) {
    emit('next', { role_template_id: selectedRole.value });
  }
}

onMounted(async () => {
  try {
    const response = await onboardingApi.getRoleTemplates();
    roleTemplates.value = response.data;
  } catch (error) {
    console.error('Failed to load role templates:', error);
    // Fallback to empty array - UI will show no roles
  } finally {
    loading.value = false;
  }
});
</script>

// coordinator-web/UISPEC/src/components/onboarding/RoleSelectionStep.tsx
import React, { useState } from 'react';
import { Phone, Calendar, Truck, Utensils, Headset, Shield, CheckCircle, TrendingUp, DollarSign, Megaphone, ClipboardList, ArrowRight } from 'lucide-react';
import { RoleCard } from './RoleCard';
import { cn } from '../../lib/utils';
const INBOUND_ROLES = [{
  id: 'receptionist',
  title: 'Receptionist',
  price: '$49/mo',
  description: 'Answer calls, route inquiries',
  icon: Phone
}, {
  id: 'scheduler',
  title: 'Appointment Scheduler',
  price: '$59/mo',
  description: 'Book new appointments',
  icon: Calendar
}, {
  id: 'dispatcher',
  title: 'Dispatcher',
  price: '$59/mo',
  description: 'Schedule service calls',
  icon: Truck
}, {
  id: 'hostess',
  title: 'Hostess',
  price: '$49/mo',
  description: 'Take reservations',
  icon: Utensils
}, {
  id: 'support',
  title: 'Support Agent',
  price: '$59/mo',
  description: 'Resolve customer issues',
  icon: Headset
}, {
  id: 'tipline',
  title: 'Tip Line Operator',
  price: '$69/mo',
  description: 'Collect confidential tips',
  icon: Shield
}];
const OUTBOUND_ROLES = [{
  id: 'confirmer',
  title: 'Appointment Confirmer',
  price: '$49/mo',
  description: 'Confirm upcoming appointments',
  icon: CheckCircle
}, {
  id: 'sales',
  title: 'Inside Sales Rep',
  price: '$79/mo',
  description: 'Book sales appointments',
  icon: TrendingUp
}, {
  id: 'collector',
  title: 'Bill Collector',
  price: '$69/mo',
  description: 'Secure payment commitments',
  icon: DollarSign
}, {
  id: 'introducer',
  title: 'Product Introducer',
  price: '$59/mo',
  description: 'Announce new offerings',
  icon: Megaphone
}, {
  id: 'survey',
  title: 'Survey Conductor',
  price: '$49/mo',
  description: 'Gather customer feedback',
  icon: ClipboardList
}];
interface RoleSelectionStepProps {
  onNext: () => void;
}
export function RoleSelectionStep({
  onNext
}: RoleSelectionStepProps) {
  const [selectedRole, setSelectedRole] = useState<string | null>(null);
  return <div className="w-full animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="text-center mb-8">
        <h1 className="text-3xl md:text-4xl font-heading font-bold text-[#1B4F72] mb-2">
          Choose Your Coordinator
        </h1>
        <p className="text-lg text-slate-600">
          What role do you need help with?
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
        {/* Inbound Column */}
        <div className="space-y-4">
          <div className="flex items-center gap-3 mb-4 px-1">
            <div className="h-px flex-1 bg-slate-200"></div>
            <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider">
              Inbound Roles
            </h2>
            <div className="h-px flex-1 bg-slate-200"></div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 gap-4">
            {INBOUND_ROLES.map(role => <RoleCard key={role.id} {...role} isSelected={selectedRole === role.id} onSelect={setSelectedRole} />)}
          </div>
        </div>

        {/* Outbound Column */}
        <div className="space-y-4">
          <div className="flex items-center gap-3 mb-4 px-1">
            <div className="h-px flex-1 bg-slate-200"></div>
            <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider">
              Outbound Roles
            </h2>
            <div className="h-px flex-1 bg-slate-200"></div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 gap-4">
            {OUTBOUND_ROLES.map(role => <RoleCard key={role.id} {...role} isSelected={selectedRole === role.id} onSelect={setSelectedRole} />)}
          </div>
        </div>
      </div>

      <div className="mt-12 text-center">
        <button onClick={onNext} className={cn('flex items-center justify-center gap-2 mx-auto px-8 py-3 rounded-lg font-semibold text-white transition-all duration-200 shadow-lg hover:shadow-xl', selectedRole ? 'bg-[#F59E0B] hover:bg-[#D97706] hover:-translate-y-0.5' : 'bg-slate-300 cursor-not-allowed')} disabled={!selectedRole}>
          Continue to Next Step
          <ArrowRight size={18} />
        </button>
        <p className="mt-4 text-sm text-slate-400 flex items-center justify-center gap-1.5">
          <span className="text-[#F59E0B]">⚡</span> Setup takes less than 60
          seconds
        </p>
      </div>
    </div>;
}
