// scanner-web/src/pages/ProfilePage.vue
<template>
  <ProfilePageTemplate
    app-name="Scanner"
    app-tagline="Website Health Monitoring"
    :logo-icon="ScanSearch"
    logo-gradient="bg-gradient-to-br from-green-500 to-teal-600 shadow-green-500/20"
    tagline-color="text-green-400"
    cover-gradient="bg-gradient-to-r from-green-600 via-teal-600 to-emerald-600"
    :user-data="userData"
    :show-business-profile="false"
  >
    <template #profile-images>
      <div class="flex gap-4">
        <div class="relative group">
          <div class="w-32 h-32 rounded-2xl bg-gradient-to-br from-green-500 to-teal-600 flex items-center justify-center text-white text-4xl font-bold border-4 border-slate-800 shadow-xl overflow-hidden">
            <img v-if="profileData.profileImage" :src="profileData.profileImage" alt="Profile" class="w-full h-full object-cover" />
            <template v-else>{{ profileData.avatarInitials }}</template>
          </div>
          <button
            v-if="isEditing"
            @click="handleImageUpload('profile')"
            class="absolute bottom-2 right-2 p-2 rounded-lg bg-green-600 text-white hover:bg-green-700 transition-colors shadow-lg"
          >
            <Camera class="h-4 w-4" />
          </button>
        </div>
      </div>
    </template>

    <template #badges>
      <div class="flex items-center gap-2 flex-wrap">
        <div class="px-3 py-1 rounded-full bg-gradient-to-r from-green-600 to-teal-600 text-white text-xs font-bold flex items-center gap-1">
          <Crown class="h-3 w-3" />
          {{ subscriptionStore.plan }}
        </div>
      </div>
    </template>

    <template #edit-button>
      <button
        @click="isEditing ? handleSave() : isEditing = true"
        :class="['flex items-center gap-2 px-4 py-2 rounded-lg font-semibold transition-all', isEditing ? 'bg-gradient-to-r from-green-600 to-teal-600 text-white shadow-lg shadow-green-500/30' : 'bg-slate-700 text-slate-300 hover:bg-slate-600']"
      >
        <template v-if="isEditing">
          <Save class="h-4 w-4" />
          Save Changes
        </template>
        <template v-else>
          <Edit2 class="h-4 w-4" />
          Edit Profile
        </template>
      </button>
    </template>

    <template #stats>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div
          v-for="stat in stats"
          :key="stat.label"
          class="p-4 rounded-xl bg-slate-900/50 border-2 border-slate-700"
        >
          <component :is="stat.icon" :class="['h-5 w-5', stat.color, 'mb-2']" />
          <p class="text-2xl font-bold text-white mb-1">
            {{ stat.value }}
          </p>
          <p class="text-xs text-slate-400">{{ stat.label }}</p>
        </div>
      </div>
    </template>

    <template #personal-profile-fields>
      <div class="space-y-6">
        <!-- Bio -->
        <div>
          <label class="block text-sm font-semibold text-slate-300 mb-2">
            Bio
          </label>
          <textarea
            v-if="isEditing"
            v-model="profileData.bio"
            rows="3"
            class="w-full px-4 py-3 bg-slate-900/50 border-2 border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-green-500 transition-colors resize-none"
          />
          <p v-else class="text-slate-300">{{ profileData.bio || 'No bio yet' }}</p>
        </div>

        <!-- Contact Info Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-semibold text-slate-300 mb-2">
              <Mail class="inline h-4 w-4 mr-1" />
              Email
            </label>
            <input
              v-if="isEditing"
              v-model="profileData.email"
              type="email"
              class="w-full px-4 py-3 bg-slate-900/50 border-2 border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-green-500 transition-colors"
            />
            <p v-else class="text-slate-300">{{ profileData.email }}</p>
          </div>

          <div>
            <label class="block text-sm font-semibold text-slate-300 mb-2">
              <Phone class="inline h-4 w-4 mr-1" />
              Phone
            </label>
            <input
              v-if="isEditing"
              v-model="profileData.phone"
              type="tel"
              class="w-full px-4 py-3 bg-slate-900/50 border-2 border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-green-500 transition-colors"
            />
            <p v-else class="text-slate-300">{{ profileData.phone || 'Not set' }}</p>
          </div>
        </div>
      </div>
    </template>

    <template #account-info>
      <div class="space-y-3">
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-400">Member since</span>
          <span class="text-sm font-semibold text-white">
            {{ profileData.joinDate }}
          </span>
        </div>
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-400">Plan</span>
          <span class="text-sm font-semibold text-green-400">
            {{ subscriptionStore.plan }}
          </span>
        </div>
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-400">Status</span>
          <span class="text-sm font-semibold text-green-400">
            Active
          </span>
        </div>
      </div>
    </template>

    <template #upgrade-button>
      <button
        class="w-full mt-4 px-4 py-2 bg-gradient-to-r from-green-600 to-teal-600 text-white font-semibold rounded-lg shadow-lg hover:shadow-xl transition-all"
        @click="$router.push('/subscribe')"
      >
        Upgrade Plan
      </button>
    </template>

    <template #quick-actions>
      <div class="space-y-2">
        <button class="w-full text-left px-4 py-2 rounded-lg bg-slate-900/50 text-slate-300 hover:bg-slate-700 transition-colors">
          Change Password
        </button>
        <button class="w-full text-left px-4 py-2 rounded-lg bg-slate-900/50 text-slate-300 hover:bg-slate-700 transition-colors">
          Privacy Settings
        </button>
        <button class="w-full text-left px-4 py-2 rounded-lg bg-slate-900/50 text-red-400 hover:bg-red-500/20 transition-colors">
          Delete Account
        </button>
      </div>
    </template>
  </ProfilePageTemplate>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import {
  ScanSearch,
  Mail,
  Phone,
  Edit2,
  Camera,
  Save,
  Crown,
  CheckSquare,
  Globe,
} from 'lucide-vue-next'
// @ts-ignore
import ProfilePageTemplate from '@taskjuggler/ui/templates/auth/ProfilePageTemplate.vue'
import { useAuthStore } from '@/stores/auth'
import { useSubscriptionStore } from '@/stores/subscription'
import api from '@/utils/api'

const authStore = useAuthStore()
const subscriptionStore = useSubscriptionStore()

const isEditing = ref(false)
const saving = ref(false)

const profileData = reactive({
  name: '',
  email: '',
  phone: '',
  bio: '',
  joinDate: '',
  profileImage: '',
  avatarInitials: '',
})

const userData = computed(() => ({
  name: profileData.name || authStore.user?.name || 'User',
  email: profileData.email || authStore.user?.email || '',
  role: 'Scanner User',
  company: '',
}))

const stats = computed(() => [
  {
    label: 'Sites Monitored',
    value: '0',
    icon: Globe,
    color: 'text-green-400',
  },
  {
    label: 'Scans Completed',
    value: '0',
    icon: CheckSquare,
    color: 'text-teal-400',
  },
])

async function loadProfile() {
  try {
    await authStore.fetchUser()
    if (authStore.user) {
      const user = authStore.user
      profileData.name = user.name || ''
      profileData.email = user.email || ''
      profileData.phone = (user as any).phone || ''
      profileData.avatarInitials = user.name
        ? user.name
            .split(' ')
            .map((n: string) => n[0])
            .join('')
            .toUpperCase()
            .slice(0, 2)
        : 'SC'
      profileData.joinDate = (user as any).created_at
        ? new Date((user as any).created_at).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
        : 'Recently'
    }
  } catch (error) {
    // Handle error
  }
}

async function handleSave() {
  saving.value = true
  try {
    await api.put('/auth/user', {
      name: profileData.name,
      email: profileData.email,
      phone: profileData.phone,
    })
    await authStore.fetchUser()
    isEditing.value = false
  } catch (error: any) {
    console.error('Failed to save profile:', error)
  } finally {
    saving.value = false
  }
}

function handleImageUpload(type: 'profile') {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = 'image/*'
  input.onchange = async (e: Event) => {
    const file = (e.target as HTMLInputElement).files?.[0]
    if (file) {
      try {
        const formData = new FormData()
        formData.append('image', file)
        formData.append('type', type)
        
        // For now, create object URL
        const url = URL.createObjectURL(file)
        if (type === 'profile') {
          profileData.profileImage = url
        }
      } catch (error) {
        // Handle error
      }
    }
  }
  input.click()
}

onMounted(() => {
  loadProfile()
})
</script>

// ideacircuit-web/src/pages/ProfilePage.tsx
import React, { useState, useEffect } from 'react';
import { NavigationMenu } from '../components/NavigationMenu';
import { FileExplorer } from '../components/FileExplorer';
import { UserIcon, SettingsIcon, BellIcon, KeyIcon, LogOutIcon, CameraIcon, EditIcon, SaveIcon, MailIcon, PhoneIcon, GlobeIcon, ClockIcon, FolderIcon, VideoIcon, FileIcon, BriefcaseIcon } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import { useAuthStore } from '../stores/auth';
import api from '../services/api';

interface ActivityItem {
  id: number;
  type: 'call' | 'file';
  title: string;
  date: string;
  duration?: string;
}

export const ProfilePage: React.FC = () => {
  const { user, logout } = useAuth();
  const { user: storeUser } = useAuthStore();
  const [activeTab, setActiveTab] = useState('profile');
  const [isEditing, setIsEditing] = useState(false);
  const [userData, setUserData] = useState({
    firstName: storeUser?.name?.split(' ')[0] || '',
    lastName: storeUser?.name?.split(' ').slice(1).join(' ') || '',
    email: storeUser?.email || '',
    phone: '',
    company: '',
    role: '',
    location: '',
    timezone: 'UTC',
    bio: '',
    profilePicture: ''
  });
  const [formData, setFormData] = useState({ ...userData });
  const [activityData, setActivityData] = useState<ActivityItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadUserProfile();
    loadActivity();
  }, [user]);

  const loadUserProfile = async () => {
    if (!user) return;
    
    try {
      const response = await api.get('/ideacircuit/user/profile');
      const profile = response.data.data || response.data;
      
      if (profile) {
        const nameParts = (profile.name || storeUser?.name || '').split(' ');
        setUserData({
          firstName: nameParts[0] || '',
          lastName: nameParts.slice(1).join(' ') || '',
          email: profile.email || storeUser?.email || '',
          phone: profile.phone || '',
          company: profile.company || '',
          role: profile.role || '',
          location: profile.location || '',
          timezone: profile.timezone || 'UTC',
          bio: profile.bio || '',
          profilePicture: profile.profile_picture || ''
        });
        setFormData({
          firstName: nameParts[0] || '',
          lastName: nameParts.slice(1).join(' ') || '',
          email: profile.email || storeUser?.email || '',
          phone: profile.phone || '',
          company: profile.company || '',
          role: profile.role || '',
          location: profile.location || '',
          timezone: profile.timezone || 'UTC',
          bio: profile.bio || '',
          profilePicture: profile.profile_picture || ''
        });
      }
    } catch (error) {
      console.error('Error loading user profile:', error);
    }
  };

  const loadActivity = async () => {
    setLoading(true);
    try {
      const response = await api.get('/ideacircuit/user/activity');
      const activities = response.data.data || response.data;
      setActivityData(Array.isArray(activities) ? activities : []);
    } catch (error) {
      console.error('Error loading activity:', error);
      setActivityData([]);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value
    });
  };

  const handleSave = async () => {
    try {
      await api.put('/ideacircuit/user/profile', {
        name: `${formData.firstName} ${formData.lastName}`.trim(),
        email: formData.email,
        phone: formData.phone,
        company: formData.company,
        role: formData.role,
        location: formData.location,
        timezone: formData.timezone,
        bio: formData.bio
      });
      setUserData({ ...formData });
      setIsEditing(false);
    } catch (error) {
      console.error('Error saving profile:', error);
    }
  };

  const handleCancel = () => {
    setFormData({ ...userData });
    setIsEditing(false);
  };

  const handleLogout = async () => {
    await logout();
    window.location.href = '/login';
  };

  return (
    <div className="flex flex-col h-screen bg-bg-secondary">
      {/* Header */}
      <div className="glass-subtle border-b border-border p-4 flex justify-between items-center">
        <h1 className="text-headline font-semibold text-text-primary">My Profile</h1>
        <div className="flex space-x-2 items-center">
          <button 
            className="p-2 rounded-full hover:bg-bg-secondary min-h-[44px] min-w-[44px] flex items-center justify-center transition-colors duration-fast"
            aria-label="Notifications"
          >
            <BellIcon size={20} className="text-text-secondary" />
          </button>
          <NavigationMenu />
        </div>
      </div>
      
      {/* Content */}
      <div className="flex-1 overflow-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col md:flex-row gap-6">
            {/* Sidebar */}
            <div className="md:w-64">
              <div className="glass-standard rounded-lg overflow-hidden shadow-1 sticky top-8">
                <div className="p-6 text-center">
                  <div className="relative inline-block">
                    <img 
                      src={userData.profilePicture || `https://ui-avatars.com/api/?name=${encodeURIComponent(userData.firstName + ' ' + userData.lastName)}&background=007AFF&color=fff`} 
                      alt="Profile" 
                      className="h-24 w-24 rounded-full mx-auto object-cover" 
                    />
                    <button 
                      className="absolute bottom-0 right-0 bg-primary text-white p-1.5 rounded-full min-h-[32px] min-w-[32px] flex items-center justify-center hover:bg-primary-hover transition-colors duration-fast"
                      aria-label="Change profile picture"
                    >
                      <CameraIcon size={16} />
                    </button>
                  </div>
                  <h2 className="mt-4 text-title-large font-semibold text-text-primary">
                    {userData.firstName} {userData.lastName}
                  </h2>
                  <p className="text-text-secondary text-body-small">
                    {userData.role} {userData.company ? `at ${userData.company}` : ''}
                  </p>
                </div>
                <div className="border-t border-border">
                  <nav className="flex flex-col">
                    <button 
                      className={`flex items-center px-6 py-3 text-body-medium font-medium min-h-[44px] transition-colors duration-fast ${
                        activeTab === 'profile' 
                          ? 'bg-primary-light text-primary border-l-4 border-primary' 
                          : 'text-text-secondary hover:bg-bg-secondary hover:text-text-primary'
                      }`} 
                      onClick={() => setActiveTab('profile')}
                    >
                      <UserIcon size={18} className="mr-3" />
                      Profile Information
                    </button>
                    <button 
                      className={`flex items-center px-6 py-3 text-body-medium font-medium min-h-[44px] transition-colors duration-fast ${
                        activeTab === 'files' 
                          ? 'bg-primary-light text-primary border-l-4 border-primary' 
                          : 'text-text-secondary hover:bg-bg-secondary hover:text-text-primary'
                      }`} 
                      onClick={() => setActiveTab('files')}
                    >
                      <FolderIcon size={18} className="mr-3" />
                      My Files
                    </button>
                    <button 
                      className={`flex items-center px-6 py-3 text-body-medium font-medium min-h-[44px] transition-colors duration-fast ${
                        activeTab === 'activity' 
                          ? 'bg-primary-light text-primary border-l-4 border-primary' 
                          : 'text-text-secondary hover:bg-bg-secondary hover:text-text-primary'
                      }`} 
                      onClick={() => setActiveTab('activity')}
                    >
                      <ClockIcon size={18} className="mr-3" />
                      Recent Activity
                    </button>
                    <button 
                      className={`flex items-center px-6 py-3 text-body-medium font-medium min-h-[44px] transition-colors duration-fast ${
                        activeTab === 'settings' 
                          ? 'bg-primary-light text-primary border-l-4 border-primary' 
                          : 'text-text-secondary hover:bg-bg-secondary hover:text-text-primary'
                      }`} 
                      onClick={() => setActiveTab('settings')}
                    >
                      <SettingsIcon size={18} className="mr-3" />
                      Account Settings
                    </button>
                    <button 
                      className={`flex items-center px-6 py-3 text-body-medium font-medium min-h-[44px] transition-colors duration-fast ${
                        activeTab === 'security' 
                          ? 'bg-primary-light text-primary border-l-4 border-primary' 
                          : 'text-text-secondary hover:bg-bg-secondary hover:text-text-primary'
                      }`} 
                      onClick={() => setActiveTab('security')}
                    >
                      <KeyIcon size={18} className="mr-3" />
                      Security
                    </button>
                  </nav>
                </div>
                <div className="p-6 border-t border-border">
                  <button 
                    className="w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-1 text-label font-medium text-white bg-destructive hover:bg-destructive/90 min-h-[44px] transition-colors duration-fast"
                    onClick={handleLogout}
                  >
                    <LogOutIcon size={16} className="mr-2" />
                    Sign out
                  </button>
                </div>
              </div>
            </div>
            
            {/* Main content */}
            <div className="flex-1">
              {activeTab === 'profile' && (
                <div className="glass-standard rounded-lg overflow-hidden shadow-1">
                  <div className="p-6 border-b border-border flex justify-between items-center">
                    <h2 className="text-headline font-semibold text-text-primary">Profile Information</h2>
                    {isEditing ? (
                      <div className="flex space-x-2">
                        <button 
                          onClick={handleSave} 
                          className="px-3 py-1.5 bg-primary text-white rounded-md text-label font-medium min-h-[44px] flex items-center hover:bg-primary-hover transition-colors duration-fast"
                        >
                          <SaveIcon size={14} className="mr-1" />
                          Save
                        </button>
                        <button 
                          onClick={handleCancel} 
                          className="px-3 py-1.5 border border-border text-text-primary rounded-md text-label font-medium min-h-[44px] hover:bg-bg-secondary transition-colors duration-fast"
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <button 
                        onClick={() => setIsEditing(true)} 
                        className="px-3 py-1.5 border border-border text-text-primary rounded-md text-label font-medium min-h-[44px] flex items-center hover:bg-bg-secondary transition-colors duration-fast"
                      >
                        <EditIcon size={14} className="mr-1" />
                        Edit
                      </button>
                    )}
                  </div>
                  
                  <div className="p-6 space-y-6">
                    <div className="grid grid-cols-2 gap-6">
                      <div>
                        <label className="block text-label font-medium text-text-primary mb-2">First Name</label>
                        {isEditing ? (
                          <input
                            type="text"
                            name="firstName"
                            value={formData.firstName}
                            onChange={handleChange}
                            className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                          />
                        ) : (
                          <p className="text-body-medium text-text-primary">{userData.firstName}</p>
                        )}
                      </div>
                      <div>
                        <label className="block text-label font-medium text-text-primary mb-2">Last Name</label>
                        {isEditing ? (
                          <input
                            type="text"
                            name="lastName"
                            value={formData.lastName}
                            onChange={handleChange}
                            className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                          />
                        ) : (
                          <p className="text-body-medium text-text-primary">{userData.lastName}</p>
                        )}
                      </div>
                    </div>
                    
                    <div>
                      <label className="block text-label font-medium text-text-primary mb-2 flex items-center">
                        <MailIcon size={16} className="mr-2" />
                        Email
                      </label>
                      {isEditing ? (
                        <input
                          type="email"
                          name="email"
                          value={formData.email}
                          onChange={handleChange}
                          className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                        />
                      ) : (
                        <p className="text-body-medium text-text-primary">{userData.email}</p>
                      )}
                    </div>
                    
                    <div>
                      <label className="block text-label font-medium text-text-primary mb-2 flex items-center">
                        <PhoneIcon size={16} className="mr-2" />
                        Phone
                      </label>
                      {isEditing ? (
                        <input
                          type="tel"
                          name="phone"
                          value={formData.phone}
                          onChange={handleChange}
                          className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                        />
                      ) : (
                        <p className="text-body-medium text-text-primary">{userData.phone || 'Not provided'}</p>
                      )}
                    </div>
                    
                    <div className="grid grid-cols-2 gap-6">
                      <div>
                        <label className="block text-label font-medium text-text-primary mb-2 flex items-center">
                          <BriefcaseIcon size={16} className="mr-2" />
                          Company
                        </label>
                        {isEditing ? (
                          <input
                            type="text"
                            name="company"
                            value={formData.company}
                            onChange={handleChange}
                            className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                          />
                        ) : (
                          <p className="text-body-medium text-text-primary">{userData.company || 'Not provided'}</p>
                        )}
                      </div>
                      <div>
                        <label className="block text-label font-medium text-text-primary mb-2">Role</label>
                        {isEditing ? (
                          <input
                            type="text"
                            name="role"
                            value={formData.role}
                            onChange={handleChange}
                            className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                          />
                        ) : (
                          <p className="text-body-medium text-text-primary">{userData.role || 'Not provided'}</p>
                        )}
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-6">
                      <div>
                        <label className="block text-label font-medium text-text-primary mb-2 flex items-center">
                          <GlobeIcon size={16} className="mr-2" />
                          Location
                        </label>
                        {isEditing ? (
                          <input
                            type="text"
                            name="location"
                            value={formData.location}
                            onChange={handleChange}
                            className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                          />
                        ) : (
                          <p className="text-body-medium text-text-primary">{userData.location || 'Not provided'}</p>
                        )}
                      </div>
                      <div>
                        <label className="block text-label font-medium text-text-primary mb-2 flex items-center">
                          <ClockIcon size={16} className="mr-2" />
                          Timezone
                        </label>
                        {isEditing ? (
                          <input
                            type="text"
                            name="timezone"
                            value={formData.timezone}
                            onChange={handleChange}
                            className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 min-h-[44px]"
                          />
                        ) : (
                          <p className="text-body-medium text-text-primary">{userData.timezone}</p>
                        )}
                      </div>
                    </div>
                    
                    <div>
                      <label className="block text-label font-medium text-text-primary mb-2">Bio</label>
                      {isEditing ? (
                        <textarea
                          name="bio"
                          value={formData.bio}
                          onChange={handleChange}
                          rows={4}
                          className="w-full border border-border rounded-md px-4 py-3 text-body-large bg-bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 resize-y min-h-[88px]"
                        />
                      ) : (
                        <p className="text-body-medium text-text-primary">{userData.bio || 'No bio provided'}</p>
                      )}
                    </div>
                  </div>
                </div>
              )}
              
              {activeTab === 'files' && (
                <div className="glass-standard rounded-lg overflow-hidden shadow-1">
                  <div className="p-6 border-b border-border">
                    <h2 className="text-headline font-semibold text-text-primary">My Files</h2>
                  </div>
                  <div className="p-6">
                    <FileExplorer />
                  </div>
                </div>
              )}
              
              {activeTab === 'activity' && (
                <div className="glass-standard rounded-lg overflow-hidden shadow-1">
                  <div className="p-6 border-b border-border">
                    <h2 className="text-headline font-semibold text-text-primary">Recent Activity</h2>
                  </div>
                  <div className="p-6">
                    {loading ? (
                      <div className="text-center py-8 text-text-secondary text-body-medium">Loading activity...</div>
                    ) : activityData.length === 0 ? (
                      <div className="text-center py-8 text-text-secondary text-body-medium">No recent activity</div>
                    ) : (
                      <div className="space-y-4">
                        {activityData.map(activity => (
                          <div key={activity.id} className="flex items-center p-4 glass-subtle rounded-lg">
                            <div className={`p-2 rounded-md mr-4 ${
                              activity.type === 'call' ? 'bg-primary-light' : 'bg-bg-tertiary'
                            }`}>
                              {activity.type === 'call' ? (
                                <VideoIcon size={20} className={activity.type === 'call' ? 'text-primary' : 'text-text-secondary'} />
                              ) : (
                                <FileIcon size={20} className="text-text-secondary" />
                              )}
                            </div>
                            <div className="flex-1">
                              <h3 className="font-medium text-body-medium text-text-primary">{activity.title}</h3>
                              <p className="text-body-small text-text-secondary">{activity.date} {activity.duration && `• ${activity.duration}`}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              )}
              
              {activeTab === 'settings' && (
                <div className="glass-standard rounded-lg overflow-hidden shadow-1">
                  <div className="p-6 border-b border-border">
                    <h2 className="text-headline font-semibold text-text-primary">Account Settings</h2>
                  </div>
                  <div className="p-6">
                    <p className="text-body-medium text-text-secondary">Settings coming soon...</p>
                  </div>
                </div>
              )}
              
              {activeTab === 'security' && (
                <div className="glass-standard rounded-lg overflow-hidden shadow-1">
                  <div className="p-6 border-b border-border">
                    <h2 className="text-headline font-semibold text-text-primary">Security</h2>
                  </div>
                  <div className="p-6">
                    <p className="text-body-medium text-text-secondary">Security settings coming soon...</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
