// ideacircuit-web/src/pages/SchedulePage.vue
<template>
  <div class="flex flex-col h-screen bg-gray-50">
    <!-- Header -->
    <div class="bg-gray-800 text-white p-4 flex justify-between items-center">
      <h1 class="text-xl font-bold">Schedule Calls</h1>
      <NavigationMenu />
    </div>
    <!-- Main Content -->
    <div class="flex-1 overflow-hidden p-4 max-w-7xl mx-auto w-full">
      <div class="h-[calc(100vh-120px)]">
        <CalendarView />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import CalendarView from '@/components/CalendarView.vue';
import NavigationMenu from '@/components/NavigationMenu.vue';
</script>

// ideacircuit-web/src/pages/SchedulePage.tsx
import React from 'react';
import { CalendarView } from '../components/CalendarView';
import { NavigationMenu } from '../components/NavigationMenu';
export const SchedulePage = () => {
  return <div className="flex flex-col h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-gray-800 text-white p-4 flex justify-between items-center">
        <h1 className="text-xl font-bold">Schedule Calls</h1>
        <NavigationMenu />
      </div>
      {/* Main Content */}
      <div className="flex-1 overflow-hidden p-4 max-w-7xl mx-auto w-full">
        <div className="h-[calc(100vh-120px)]">
          <CalendarView />
        </div>
      </div>
    </div>;
};
