// ideacircuit-web/src/pages/SignUpPage.vue
<template>
  <div class="min-h-screen flex flex-col justify-center bg-bg-secondary py-12 sm:px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-md">
      <div class="flex justify-center">
        <div class="w-12 h-12 bg-primary rounded-lg flex items-center justify-center text-white text-title-large font-bold">
          AI
        </div>
      </div>
      <h2 class="mt-6 text-center text-display-small font-bold text-text-primary">
        Create a new account
      </h2>
      <p class="mt-2 text-center text-body-medium text-text-secondary">
        Or
        <router-link to="/login" class="font-medium text-primary hover:text-primary-hover transition-colors duration-fast">
          sign in to your existing account
        </router-link>
      </p>
    </div>
    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
      <Card class="glass-standard py-8 px-4 shadow-2 sm:rounded-xl sm:px-10">
        <CardContent class="p-0">
          <Alert v-if="error" variant="destructive" class="mb-4">
            <AlertCircleIcon :size="20" class="mr-2" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{{ error }}</AlertDescription>
          </Alert>
          <form @submit.prevent="handleSubmit" class="space-y-6">
            <div class="space-y-2">
              <Label for="name">Full Name</Label>
              <Input
                id="name"
                name="name"
                type="text"
                autocomplete="name"
                required
                v-model="formData.name"
                placeholder="John Doe"
                class="min-h-[44px]"
              />
            </div>
            <div class="space-y-2">
              <Label for="email">Email address</Label>
              <Input
                id="email"
                name="email"
                type="email"
                autocomplete="email"
                required
                v-model="formData.email"
                placeholder="you@example.com"
                class="min-h-[44px]"
              />
            </div>
            <div class="space-y-2">
              <Label for="password">Password</Label>
              <div class="relative">
                <Input
                  id="password"
                  name="password"
                  :type="showPassword ? 'text' : 'password'"
                  autocomplete="new-password"
                  required
                  v-model="formData.password"
                  @input="updatePasswordStrength"
                  placeholder="••••••••"
                  class="pr-10 min-h-[44px]"
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  class="absolute inset-y-0 right-0 pr-3"
                  @click="showPassword = !showPassword"
                  aria-label="Toggle password visibility"
                >
                  <EyeIcon v-if="!showPassword" :size="20" />
                  <EyeOffIcon v-else :size="20" />
                </Button>
              </div>
              <div v-if="formData.password" class="mt-2 space-y-2">
                <div class="flex items-center justify-between">
                  <span class="text-caption text-text-tertiary">Password strength:</span>
                  <span :class="`text-caption font-medium ${getPasswordStrengthColor()}`">
                    {{ getPasswordStrengthText() }}
                  </span>
                </div>
                <Progress :model-value="(passwordStrength / 4) * 100" class="h-1" />
                <ul class="space-y-1">
                  <li class="text-caption flex items-center text-text-secondary">
                    <CheckCircleIcon
                      v-if="/^.{8,}$/.test(formData.password)"
                      :size="12"
                      class="text-success mr-1"
                    />
                    <AlertCircleIcon
                      v-else
                      :size="12"
                      class="text-text-tertiary mr-1"
                    />
                    At least 8 characters
                  </li>
                  <li class="text-caption flex items-center text-text-secondary">
                    <CheckCircleIcon
                      v-if="/[A-Z]/.test(formData.password)"
                      :size="12"
                      class="text-success mr-1"
                    />
                    <AlertCircleIcon
                      v-else
                      :size="12"
                      class="text-text-tertiary mr-1"
                    />
                    At least one uppercase letter
                  </li>
                  <li class="text-caption flex items-center text-text-secondary">
                    <CheckCircleIcon
                      v-if="/[0-9]/.test(formData.password)"
                      :size="12"
                      class="text-success mr-1"
                    />
                    <AlertCircleIcon
                      v-else
                      :size="12"
                      class="text-text-tertiary mr-1"
                    />
                    At least one number
                  </li>
                  <li class="text-caption flex items-center text-text-secondary">
                    <CheckCircleIcon
                      v-if="/[^A-Za-z0-9]/.test(formData.password)"
                      :size="12"
                      class="text-success mr-1"
                    />
                    <AlertCircleIcon
                      v-else
                      :size="12"
                      class="text-text-tertiary mr-1"
                    />
                    At least one special character
                  </li>
                </ul>
              </div>
            </div>
            <div class="space-y-2">
              <Label for="confirmPassword">Confirm password</Label>
              <div class="relative">
                <Input
                  id="confirmPassword"
                  name="confirmPassword"
                  :type="showPassword ? 'text' : 'password'"
                  autocomplete="new-password"
                  required
                  v-model="formData.confirmPassword"
                  placeholder="••••••••"
                  class="min-h-[44px]"
                />
                <div
                  v-if="formData.password && formData.confirmPassword"
                  class="absolute inset-y-0 right-0 pr-3 flex items-center"
                >
                  <CheckCircleIcon
                    v-if="formData.password === formData.confirmPassword"
                    :size="20"
                    class="text-success"
                  />
                  <AlertCircleIcon
                    v-else
                    :size="20"
                    class="text-destructive"
                  />
                </div>
              </div>
              <div v-if="formData.password && formData.confirmPassword" class="flex items-center">
                <span
                  :class="`text-caption ${
                    formData.password === formData.confirmPassword ? 'text-success' : 'text-destructive'
                  }`"
                >
                  {{
                    formData.password === formData.confirmPassword
                      ? 'Passwords match'
                      : 'Passwords do not match'
                  }}
                </span>
              </div>
            </div>
            <div class="flex items-center space-x-2">
              <Checkbox
                id="terms"
                :checked="agreeToTerms"
                @update:checked="agreeToTerms = $event"
              />
              <Label for="terms" class="text-body-small cursor-pointer">
                I agree to the
                <a href="#" class="font-medium text-primary hover:text-primary-hover">Terms of Service</a>
                and
                <a href="#" class="font-medium text-primary hover:text-primary-hover">Privacy Policy</a>
              </Label>
            </div>
            <Button
              type="submit"
              :disabled="isLoading"
              class="w-full min-h-[44px]"
            >
              <UserPlusIcon v-if="!isLoading" :size="20" class="mr-2" />
              <span v-if="isLoading">Creating account...</span>
              <span v-else>Create account</span>
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import {
  UserPlusIcon,
  EyeIcon,
  EyeOffIcon,
  AlertCircleIcon,
  CheckCircleIcon
} from 'lucide-vue-next';
import { useAuth } from '@/composables/useAuth';
import {
  Card,
  CardContent,
  Input,
  Label,
  Button,
  Checkbox,
  Alert,
  AlertTitle,
  AlertDescription,
  Progress
} from '@/components/ui';

const router = useRouter();
const { register } = useAuth();

const formData = ref({
  name: '',
  email: '',
  password: '',
  confirmPassword: ''
});
const showPassword = ref(false);
const agreeToTerms = ref(false);
const isLoading = ref(false);
const error = ref('');
const passwordStrength = ref(0);

const updatePasswordStrength = () => {
  const value = formData.value.password;
  let strength = 0;
  if (value.length >= 8) strength += 1;
  if (/[A-Z]/.test(value)) strength += 1;
  if (/[0-9]/.test(value)) strength += 1;
  if (/[^A-Za-z0-9]/.test(value)) strength += 1;
  passwordStrength.value = strength;
};

const getPasswordStrengthText = () => {
  if (passwordStrength.value === 0) return 'Very weak';
  if (passwordStrength.value === 1) return 'Weak';
  if (passwordStrength.value === 2) return 'Medium';
  if (passwordStrength.value === 3) return 'Strong';
  return 'Very strong';
};

const getPasswordStrengthColor = () => {
  if (passwordStrength.value === 0) return 'text-destructive';
  if (passwordStrength.value === 1) return 'text-warning';
  if (passwordStrength.value === 2) return 'text-warning';
  if (passwordStrength.value === 3) return 'text-success';
  return 'text-success';
};

const handleSubmit = async () => {
  error.value = '';
  
  if (!formData.value.name || !formData.value.email || !formData.value.password) {
    error.value = 'Please fill in all required fields';
    return;
  }
  if (formData.value.password !== formData.value.confirmPassword) {
    error.value = 'Passwords do not match';
    return;
  }
  if (passwordStrength.value < 3) {
    error.value = 'Please use a stronger password';
    return;
  }
  if (!agreeToTerms.value) {
    error.value = 'You must agree to the terms and conditions';
    return;
  }
  isLoading.value = true;
  
  try {
    const result = await register(
      formData.value.email,
      formData.value.password,
      formData.value.name
    );
    
    if (result.user) {
      router.push('/login');
    } else {
      error.value = result.error || 'Failed to create account';
    }
  } catch (err: any) {
    console.error('Signup error:', err);
    error.value = err.message || 'An error occurred. Please try again.';
  } finally {
    isLoading.value = false;
  }
};
</script>

// coordinator-web/UISPEC/src/components/auth/SignUpPage.tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Mail, Lock, User, Building2 } from 'lucide-react';
export function SignUpPage() {
  const [formData, setFormData] = useState({
    name: '',
    businessName: '',
    email: '',
    password: '',
    confirmPassword: '',
    agreeToTerms: false
  });
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Handle sign up logic here
    console.log('Sign up:', formData);
  };
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const {
      name,
      value,
      type,
      checked
    } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };
  return <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-slate-50 flex flex-col">
      {/* Header */}
      <div className="p-6">
        <Link to="/" className="inline-flex items-center gap-2 text-slate-600 hover:text-[#1B4F72] transition-colors">
          <ArrowLeft size={20} />
          Back to home
        </Link>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8 py-12">
        <div className="w-full max-w-md">
          {/* Logo */}
          <div className="text-center mb-8">
            <Link to="/" className="inline-flex items-center gap-2 mb-6">
              <div className="w-12 h-12 bg-[#1B4F72] rounded-xl flex items-center justify-center text-white font-bold text-lg">
                4C
              </div>
              <span className="text-2xl font-heading font-bold text-[#1B4F72]">
                4calls.ai
              </span>
            </Link>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">
              Create your account
            </h1>
            <p className="text-slate-600">
              Start your 14-day free trial. No credit card required.
            </p>
          </div>

          {/* Sign Up Form */}
          <div className="bg-white rounded-2xl shadow-xl border border-slate-100 p-8">
            <form onSubmit={handleSubmit} className="space-y-5">
              {/* Name */}
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-slate-700 mb-2">
                  Full name
                </label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
                  <input id="name" name="name" type="text" value={formData.name} onChange={handleChange} className="w-full pl-10 pr-4 py-3 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72] transition-colors" placeholder="John Smith" required />
                </div>
              </div>

              {/* Business Name */}
              <div>
                <label htmlFor="businessName" className="block text-sm font-medium text-slate-700 mb-2">
                  Business name
                </label>
                <div className="relative">
                  <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
                  <input id="businessName" name="businessName" type="text" value={formData.businessName} onChange={handleChange} className="w-full pl-10 pr-4 py-3 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72] transition-colors" placeholder="Acme Dental Practice" required />
                </div>
              </div>

              {/* Email */}
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-slate-700 mb-2">
                  Email address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
                  <input id="email" name="email" type="email" value={formData.email} onChange={handleChange} className="w-full pl-10 pr-4 py-3 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72] transition-colors" placeholder="you@example.com" required />
                </div>
              </div>

              {/* Password */}
              <div>
                <label htmlFor="password" className="block text-sm font-medium text-slate-700 mb-2">
                  Password
                </label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
                  <input id="password" name="password" type="password" value={formData.password} onChange={handleChange} className="w-full pl-10 pr-4 py-3 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72] transition-colors" placeholder="••••••••" required />
                </div>
                <p className="text-xs text-slate-500 mt-1">
                  Must be at least 8 characters
                </p>
              </div>

              {/* Confirm Password */}
              <div>
                <label htmlFor="confirmPassword" className="block text-sm font-medium text-slate-700 mb-2">
                  Confirm password
                </label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
                  <input id="confirmPassword" name="confirmPassword" type="password" value={formData.confirmPassword} onChange={handleChange} className="w-full pl-10 pr-4 py-3 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72] transition-colors" placeholder="••••••••" required />
                </div>
              </div>

              {/* Terms */}
              <div>
                <label className="flex items-start gap-2 cursor-pointer">
                  <input type="checkbox" name="agreeToTerms" checked={formData.agreeToTerms} onChange={handleChange} className="mt-1 rounded border-slate-300 text-[#1B4F72] focus:ring-[#1B4F72]" required />
                  <span className="text-sm text-slate-600">
                    I agree to the{' '}
                    <a href="#" className="text-[#1B4F72] hover:underline">
                      Terms of Service
                    </a>{' '}
                    and{' '}
                    <a href="#" className="text-[#1B4F72] hover:underline">
                      Privacy Policy
                    </a>
                  </span>
                </label>
              </div>

              {/* Submit Button */}
              <button type="submit" className="w-full py-3 bg-[#F59E0B] hover:bg-[#D97706] text-white font-bold rounded-lg shadow-md hover:shadow-lg transition-all duration-200">
                Create account
              </button>
            </form>

            {/* Divider */}
            <div className="relative my-6">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200"></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-white text-slate-500">
                  Or sign up with
                </span>
              </div>
            </div>

            {/* Social Sign Up */}
            <div className="grid grid-cols-2 gap-3">
              <button className="py-2.5 px-4 border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors flex items-center justify-center gap-2 text-sm font-medium text-slate-700">
                <svg className="w-5 h-5" viewBox="0 0 24 24">
                  <path fill="currentColor" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                  <path fill="currentColor" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                  <path fill="currentColor" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                  <path fill="currentColor" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                </svg>
                Google
              </button>
              <button className="py-2.5 px-4 border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors flex items-center justify-center gap-2 text-sm font-medium text-slate-700">
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.17 6.839 9.49.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.7-2.782.603-3.369-1.34-3.369-1.34-.454-1.156-1.11-1.463-1.11-1.463-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.831.092-.646.35-1.086.636-1.336-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.578 9.578 0 0112 6.836c.85.004 1.705.114 2.504.336 1.909-1.294 2.747-1.025 2.747-1.025.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.578.688.48C19.138 20.167 22 16.418 22 12c0-5.523-4.477-10-10-10z" />
                </svg>
                GitHub
              </button>
            </div>
          </div>

          {/* Login Link */}
          <p className="text-center mt-6 text-sm text-slate-600">
            Already have an account?{' '}
            <Link to="/login" className="text-[#1B4F72] hover:underline font-semibold">
              Sign in
            </Link>
          </p>
        </div>
      </div>
    </div>;
}
