// _legacy_apps/ideacircuit-web/src/App.vue
<template>
  <div class="w-full min-h-screen bg-white">
    <Navbar />
    <HeroSection />
    <FeaturesSection />
    <UseCasesSection />
    <ScreensShowcaseSection />
    <TestimonialsSection />
    <PricingSection />
    <CtaSection />
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Navbar from './components/Navbar.vue';
import HeroSection from './components/HeroSection.vue';
import FeaturesSection from './components/FeaturesSection.vue';
import UseCasesSection from './components/UseCasesSection.vue';
import ScreensShowcaseSection from './components/ScreensShowcaseSection.vue';
import TestimonialsSection from './components/TestimonialsSection.vue';
import PricingSection from './components/PricingSection.vue';
import CtaSection from './components/CtaSection.vue';
import Footer from './components/Footer.vue';
</script>

// ideacircuit-web/src/App.tsx
import { Navbar } from './components/Navbar';
import { HeroSection } from './components/HeroSection';
import { FeaturesSection } from './components/FeaturesSection';
import { UseCasesSection } from './components/UseCasesSection';
import { ScreensShowcaseSection } from './components/ScreensShowcaseSection';
import { TestimonialsSection } from './components/TestimonialsSection';
import { PricingSection } from './components/PricingSection';
import { CtaSection } from './components/CtaSection';
import { Footer } from './components/Footer';

export function App() {
  return (
    <div className="w-full min-h-screen bg-white">
      <Navbar />
      <HeroSection />
      <FeaturesSection />
      <UseCasesSection />
      <ScreensShowcaseSection />
      <TestimonialsSection />
      <PricingSection />
      <CtaSection />
      <Footer />
    </div>
  );
}
