// 4doctors-web/src/pages/Settings.vue
<template>
  <div class="min-h-screen bg-slate-50 font-sans p-6">
    <header class="mb-8">
      <h1 class="text-3xl font-bold text-slate-900">Settings</h1>
      <p class="text-slate-500">Manage your practice configuration</p>
    </header>

    <div class="flex flex-col md:flex-row gap-8 max-w-6xl mx-auto">
      <!-- Sidebar Nav -->
      <nav class="w-full md:w-64 space-y-1">
          <button 
            @click="activeTab = 'practice'" 
            class="w-full text-left px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="[activeTab === 'practice' ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100']"
          >
            Practice Profile
          </button>
          <button 
             @click="activeTab = 'users'"
            class="w-full text-left px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="[activeTab === 'users' ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100']"
          >
            Users & Roles
          </button>
           <button 
             @click="activeTab = 'billing'"
            class="w-full text-left px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="[activeTab === 'billing' ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100']"
          >
            Billing & Invoices
          </button>
           <button 
             @click="activeTab = 'notifications'"
            class="w-full text-left px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="[activeTab === 'notifications' ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100']"
          >
            Notifications
          </button>
      </nav>

      <!-- Content Area -->
      <div class="flex-1 bg-white rounded-xl shadow-sm border border-slate-200 p-8 min-h-[500px]">
          
          <!-- Practice Profile -->
          <div v-if="activeTab === 'practice'" class="space-y-6">
              <h2 class="text-xl font-bold text-slate-900 border-b pb-4">Practice Details</h2>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                      <label class="block text-sm font-medium text-slate-700 mb-1">Practice Name</label>
                      <input type="text" value="Downtown Medical Group" class="w-full p-2 border border-slate-300 rounded-lg">
                  </div>
                   <div>
                      <label class="block text-sm font-medium text-slate-700 mb-1">Specialty</label>
                      <input type="text" value="Family Medicine" class="w-full p-2 border border-slate-300 rounded-lg">
                  </div>
                  <div class="md:col-span-2">
                       <label class="block text-sm font-medium text-slate-700 mb-1">Address</label>
                      <input type="text" value="123 Main St, Suite 400, New York, NY 10001" class="w-full p-2 border border-slate-300 rounded-lg">
                  </div>
              </div>
              <div class="pt-4">
                  <button class="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">Save Changes</button>
              </div>
          </div>

          <!-- Users -->
          <div v-if="activeTab === 'users'" class="space-y-6">
              <div class="flex justify-between items-center border-b pb-4">
                  <h2 class="text-xl font-bold text-slate-900">Use Management</h2>
                  <button class="px-3 py-1.5 bg-blue-600 text-white rounded text-sm font-medium">Invite User</button>
              </div>
              <table class="min-w-full">
                  <thead>
                      <tr class="text-left text-xs font-medium text-slate-500 uppercase">
                          <th class="pb-3">Name</th>
                          <th class="pb-3">Role</th>
                          <th class="pb-3">Status</th>
                          <th class="pb-3 text-right">Actions</th>
                      </tr>
                  </thead>
                  <tbody class="divide-y divide-slate-100 text-sm">
                      <tr>
                          <td class="py-3 font-medium text-slate-900">Dr. Sarah Connor</td>
                          <td class="py-3 text-slate-600">Administrator</td>
                          <td class="py-3"><span class="px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs">Active</span></td>
                          <td class="py-3 text-right text-blue-600 hover:underline cursor-pointer">Edit</td>
                      </tr>
                       <tr>
                          <td class="py-3 font-medium text-slate-900">Nurse Jackie</td>
                          <td class="py-3 text-slate-600">Nurse</td>
                          <td class="py-3"><span class="px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-xs">Active</span></td>
                          <td class="py-3 text-right text-blue-600 hover:underline cursor-pointer">Edit</td>
                      </tr>
                  </tbody>
              </table>
          </div>

          <!-- Billing -->
          <div v-if="activeTab === 'billing'" class="text-center py-12 text-slate-400">
              <p>Billing settings coming soon.</p>
          </div>

           <!-- Notifications -->
          <div v-if="activeTab === 'notifications'" class="space-y-6">
              <h2 class="text-xl font-bold text-slate-900 border-b pb-4">Preferences</h2>
              <div class="space-y-4">
                  <div class="flex items-center justify-between">
                      <div>
                          <p class="font-medium text-slate-900">Email Notifications</p>
                          <p class="text-sm text-slate-500">Receive daily digest of appointments</p>
                      </div>
                      <div class="w-10 h-5 bg-blue-600 rounded-full relative cursor-pointer"><div class="absolute right-0.5 top-0.5 w-4 h-4 bg-white rounded-full"></div></div>
                  </div>
                   <div class="flex items-center justify-between">
                      <div>
                          <p class="font-medium text-slate-900">SMS Alerts</p>
                          <p class="text-sm text-slate-500">Get notified for urgent lab results</p>
                      </div>
                      <div class="w-10 h-5 bg-slate-200 rounded-full relative cursor-pointer"><div class="absolute left-0.5 top-0.5 w-4 h-4 bg-white rounded-full"></div></div>
                  </div>
              </div>
          </div>

      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const activeTab = ref('practice');
</script>

// coordinator-web/UISPEC/src/components/settings/Settings.tsx
import React, { useState } from 'react';
import { User, Building2, Phone, Bell, Plug, Users, Shield, Code } from 'lucide-react';
import { cn } from '../../lib/utils';
import { BusinessProfile } from './BusinessProfile';
import { PhoneNumbers } from './PhoneNumbers';
import { Integrations } from './Integrations';
import { TeamMembers } from './TeamMembers';
import { Security } from './Security';
import { ApiAccess } from './ApiAccess';
export function Settings() {
  const [activeSection, setActiveSection] = useState('business');
  const [notifications, setNotifications] = useState({
    dailySummary: true,
    callTransferred: true,
    missedCalls: false,
    weeklyReport: true
  });
  const sections = [{
    id: 'general',
    label: 'General',
    icon: User
  }, {
    id: 'business',
    label: 'Business Profile',
    icon: Building2
  }, {
    id: 'phone',
    label: 'Phone Numbers',
    icon: Phone
  }, {
    id: 'notifications',
    label: 'Notifications',
    icon: Bell
  }, {
    id: 'integrations',
    label: 'Integrations',
    icon: Plug
  }, {
    id: 'team',
    label: 'Team Members',
    icon: Users
  }, {
    id: 'security',
    label: 'Security',
    icon: Shield
  }, {
    id: 'api',
    label: 'API Access',
    icon: Code
  }];
  return <div className="flex gap-6 min-h-[calc(100vh-200px)]">
      {/* Left Sidebar */}
      <div className="w-64 flex-shrink-0">
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-2 sticky top-6">
          <nav className="space-y-1">
            {sections.map(section => <button key={section.id} onClick={() => setActiveSection(section.id)} className={cn('w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors text-left', activeSection === section.id ? 'bg-blue-50 text-[#1B4F72]' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900')}>
                <section.icon size={18} />
                {section.label}
              </button>)}
          </nav>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1">
        {/* Business Profile */}
        {activeSection === 'business' && <BusinessProfile />}

        {/* Phone Numbers */}
        {activeSection === 'phone' && <PhoneNumbers />}

        {/* Integrations */}
        {activeSection === 'integrations' && <Integrations />}

        {/* Team Members */}
        {activeSection === 'team' && <TeamMembers />}

        {/* Security */}
        {activeSection === 'security' && <Security />}

        {/* API Access */}
        {activeSection === 'api' && <ApiAccess />}

        {/* General Settings */}
        {activeSection === 'general' && <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 space-y-8">
            <div>
              <h2 className="text-2xl font-bold text-[#1B4F72] mb-1">
                General Settings
              </h2>
              <p className="text-slate-500">
                Manage your account and default settings
              </p>
            </div>

            {/* Account Information */}
            <section className="space-y-4">
              <h3 className="text-lg font-semibold text-slate-900 pb-2 border-b border-slate-100">
                Account Information
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Organization Name
                  </label>
                  <input type="text" defaultValue="Acme Dental Practice" className="w-full px-3 py-2 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72]" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Account Email
                  </label>
                  <input type="email" defaultValue="admin@acmedental.com" className="w-full px-3 py-2 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72]" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Timezone
                  </label>
                  <select className="w-full px-3 py-2 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#1B4F72]/20 focus:border-[#1B4F72] bg-white">
                    <option>Pacific Time (PT)</option>
                    <option>Mountain Time (MT)</option>
                    <option>Central Time (CT)</option>
                    <option>Eastern Time (ET)</option>
                  </select>
                </div>
              </div>
              <button className="px-4 py-2 bg-[#1B4F72] text-white font-medium rounded-lg hover:bg-[#153e5a] transition-colors flex items-center gap-2">
                Save Changes
              </button>
            </section>
          </div>}

        {/* Notifications Settings */}
        {activeSection === 'notifications' && <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 space-y-8">
            <div>
              <h2 className="text-2xl font-bold text-[#1B4F72] mb-1">
                Notifications
              </h2>
              <p className="text-slate-500">Manage how you receive updates</p>
            </div>

            <section className="space-y-4">
              {[{
            key: 'dailySummary',
            label: 'Email me daily summary',
            desc: 'Receive a daily digest of activity'
          }, {
            key: 'callTransferred',
            label: 'Email me when call transferred',
            desc: 'Get notified when a call is transferred to you'
          }, {
            key: 'missedCalls',
            label: 'SMS me for missed calls',
            desc: "Text notification for calls that weren't answered"
          }, {
            key: 'weeklyReport',
            label: 'Weekly performance report',
            desc: 'Comprehensive weekly analytics report'
          }].map(notif => <div key={notif.key} className="flex justify-between items-start p-4 border border-slate-200 rounded-lg">
                  <div className="flex-1">
                    <h4 className="font-medium text-slate-900 mb-1">
                      {notif.label}
                    </h4>
                    <p className="text-sm text-slate-500">{notif.desc}</p>
                  </div>
                  <button onClick={() => setNotifications(prev => ({
              ...prev,
              [notif.key]: !prev[notif.key as keyof typeof prev]
            }))} className={cn('relative inline-flex h-6 w-11 items-center rounded-full transition-colors ml-4 flex-shrink-0', notifications[notif.key as keyof typeof notifications] ? 'bg-[#1B4F72]' : 'bg-slate-200')}>
                    <span className={cn('inline-block h-4 w-4 transform rounded-full bg-white transition-transform', notifications[notif.key as keyof typeof notifications] ? 'translate-x-6' : 'translate-x-1')} />
                  </button>
                </div>)}
            </section>
          </div>}

        {/* Placeholder for other sections */}
        {!['general', 'business', 'phone', 'notifications', 'integrations', 'team', 'security', 'api'].includes(activeSection) && <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 text-center py-20">
            <h2 className="text-2xl font-bold text-slate-800 mb-2">
              {sections.find(s => s.id === activeSection)?.label}
            </h2>
            <p className="text-slate-500">
              This section is under construction.
            </p>
          </div>}
      </div>
    </div>;
}
